[cal_conf]
normal_cycles = 7
var_behavior_cycles = 37

[exec_conf]
asan_options = "abort_on_error=1:detect_leaks=0:symbolize=0:allocator_may_return_null=1:detect_stack_use_after_return=1"
func_info_file = "xed_func_list.json"
mem_limit = 500
msan_options = "exit_code=86:symbolize=0:msan_track_origins=0"
tmout = 50
use_forkserver = true
use_func_trace = false

[exec_conf.exec_symb]
args = ["/home/docker/test-xed-fot/xed-func", "-v", "0", "-xv", "0", "-i", "@@"]
pos = 6
qemu_mode = false

[fz_conf]
bind_cpu = false
exit_nonzero_as_crash = false
ignored_signals = []
mode = "Normal"
scorer = "Simple"
workers = 1

[fz_conf.conductor_conf]
report_duration = 180000

[fz_conf.sync_conf]
duration = 200
execs = 5

[io_conf]
in_folder = "/home/docker/test-xed-fot/in"
out_folder = "/home/docker/test-xed-fot/out_20181114_04_30_10"

[minimize_conf]
ck_redundant_file = false

[mut_conf]
dict_level = 0
havoc_adjust_duration = 480000
havoc_div = 1
max_dict_size = 256
max_file_len = 1600
max_token_len = 64
min_token_len = 2

[mut_conf.active_ops]
bits = 24576

[rec_conf]
interval = 2000
log_entry_info = true
proj_name = "xed"
url = "redis://127.0.0.1/"

[target_info]
defer_forkserver = true
persist_mode = false
use_asan = false
